# Generated by Django 4.2.5 on 2023-09-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.CharField(max_length=32, unique=True)),
                ("slug", models.SlugField(max_length=128, unique=True)),
            ],
            options={
                "verbose_name": "career",
                "verbose_name_plural": "career",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=128, unique=True)),
                ("slug", models.SlugField(max_length=128, unique=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Celebrity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "height",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("image", models.ImageField(upload_to="celebrities/")),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("career", models.ManyToManyField(related_name="celebrities", to="movies.career")),
            ],
            options={
                "verbose_name": "celebrity",
                "verbose_name_plural": "celebrities",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=128, unique=True)),
                ("slug", models.SlugField(max_length=128, unique=True)),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=128, unique=True)),
                ("slug", models.SlugField(max_length=128, unique=True)),
            ],
            options={
                "verbose_name": "genre",
                "verbose_name_plural": "genres",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("tagline", models.CharField(default="", max_length=255)),
                ("description", models.TextField()),
                ("poster", models.ImageField(upload_to="movies/")),
                ("link", models.URLField(max_length=128, unique=True)),
                ("year_of_production", models.PositiveSmallIntegerField()),
                ("slug", models.SlugField(max_length=155, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "Draft"), ("PB", "Published")], default="DF", max_length=2
                    ),
                ),
                ("actor", models.ManyToManyField(related_name="actors", to="movies.celebrity")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="movies.category",
                    ),
                ),
                ("country", models.ManyToManyField(related_name="movies", to="movies.country")),
                (
                    "director",
                    models.ManyToManyField(related_name="directors", to="movies.celebrity"),
                ),
                ("genre", models.ManyToManyField(related_name="movies", to="movies.genre")),
            ],
            options={
                "verbose_name": "movie",
                "verbose_name_plural": "movies",
            },
        ),
        migrations.AddField(
            model_name="celebrity",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="celebrities",
                to="movies.country",
            ),
        ),
    ]
